USE  dbCuaHangNuocGiaiKhat

INSERT INTO LOAINHANVIEN VALUES (N'Nhân Viên Thu Ngân')
INSERT INTO LOAINHANVIEN VALUES (N'Nhân Viên Kho')
INSERT INTO LOAINHANVIEN VALUES (N'Nhân Viên Pha Chế')
INSERT INTO LOAINHANVIEN VALUES (N'Nhân Viên Kế Toán')
INSERT INTO NHANVIEN VALUES (1,N'Nguyễn Van A',N'ĐH CNTT ĐHQG TPHCM',N'phuocthang@gmail.com',0921231231,N'Nam',1)
INSERT INTO NHANVIEN VALUES (2,N'Nguyễn Van B',N'ĐH CNTT ĐHQG TPHCM',N'phuocthang@gmail.com',0921231231,N'Nam',1)
INSERT INTO NHANVIEN VALUES (3,N'Nguyễn Van C',N'ĐH CNTT ĐHQG TPHCM',N'phuocthang@gmail.com',0921231231,N'Nam',1)
INSERT INTO NHANVIEN VALUES (4,N'Nguyễn Van D',N'ĐH CNTT ĐHQG TPHCM',N'phuocthang@gmail.com',0921231231,N'Nam',1)

INSERT INTO DONVITINH VALUES (N'Gói')
INSERT INTO DONVITINH VALUES (N'Lon')
INSERT INTO DONVITINH VALUES (N'Ly')
INSERT INTO DONVITINH VALUES (N'Thùng')
INSERT INTO DONVITINH VALUES (N'Chai')
INSERT INTO DONVITINH VALUES (N'ml')
INSERT INTO DONVITINH VALUES (N'g')
INSERT INTO DONVITINH VALUES (N'kg')


INSERT INTO NGUYENLIEU VALUES (N'Pepsi',120,200000,N'Lon',N'Thùng',24,10)
INSERT INTO NGUYENLIEU VALUES (N'Coca Cola',120,250000,N'Lon',N'Thùng',24,10)
INSERT INTO NGUYENLIEU VALUES (N'Red Bull',120,350000,N'Lon',N'Thùng',24,10)


INSERT INTO NHACUNGCAP VALUES (N'Công Ty Cổ Phần Tập Đoàn Trung Nguyên - Nhà Máy Cà Phê Sài Gòn',N'Lô A, Đường NA7, Khu Công Nghiệp Mỹ Phước 2, P. Mỹ Phước, Bến Cát, Bình Dương , Việt Nam',0833553292,N'')
INSERT INTO NHACUNGCAP VALUES (N'Công Ty TNHH Thực Phẩm & Nước Giải Khát A&B',N'Ấp Hòa Lân, X. Thuận Giao, H. Thuận An, Bình Dương, Việt Nam',0838261684,N'')

INSERT INTO NGUYENLIEU_NHACUNGCAP VALUES (1,2)
INSERT INTO NGUYENLIEU_NHACUNGCAP VALUES (2,2)
INSERT INTO NGUYENLIEU_NHACUNGCAP VALUES (3,2)

INSERT INTO LOAISANPHAM VALUES (N'Cà Phê')
INSERT INTO LOAISANPHAM VALUES (N'Nước Ngọt')
INSERT INTO LOAISANPHAM VALUES (N'Nước Trái Cây')
INSERT INTO LOAISANPHAM VALUES (N'Sữa')
INSERT INTO LOAISANPHAM VALUES (N'Sinh Tố')
INSERT INTO LOAISANPHAM VALUES (N'Bia - Rượu')

INSERT INTO SANPHAM VALUES (2,N'Pepsi',10000,N'Lon',N'')
INSERT INTO CHITIET_SANPHAM VALUES (1,1,1)


INSERT INTO SANPHAM VALUES (2,N'Coca Cola',12000,N'Lon',N'')
INSERT INTO CHITIET_SANPHAM VALUES (2,2,1)

INSERT INTO SANPHAM VALUES (2,N'Red Bull',11000,N'Lon',N'')
INSERT INTO CHITIET_SANPHAM VALUES (3,3,1)


INSERT INTO SANPHAM VALUES (2,N'Sản Phẩm Pha Chế Nào Đó',20000,N'Lon',N'')
INSERT INTO CHITIET_SANPHAM VALUES (4,1,1)
INSERT INTO CHITIET_SANPHAM VALUES (4,2,2)
INSERT INTO CHITIET_SANPHAM VALUES (4,3,3)


INSERT INTO PHIEUMUAHANG VALUES('2017/06/18',2,4000000,1)
INSERT INTO CHITIET_PHIEUMUAHANG VALUES(1,1,5)
INSERT INTO CHITIET_PHIEUMUAHANG VALUES(1,2,5)
INSERT INTO CHITIET_PHIEUMUAHANG VALUES(1,3,5)


INSERT INTO PHIEUNHAP VALUES(1,'2017/06/18',2,4000000)

INSERT INTO PHIEUCHI VALUES(1,4,'2017/06/18',N'Chi Trả Cho Việc Nhập Hàng',4000000)